export const de = {
  every: "Jede",
  every2: "Jeder",
  everyMinute: "Minütlich",
  hourly: "Stündlich",
  daily: "Täglich",
  weekly: "Wöchentlich",
  monthly: "Monatlich",
  yearly: "Jährlich",
  advanced: "Erweitert",
  expresion: "Ausdruck",
  seconds: "Sekunde(n)",
  minute: "Minute(n)",
  hour: "Stunde(n)",
  days: "Tag(e)",
  day: "Tag",
  month: "Monat",
  week: "Woche",
  everyWeekday: "Wochentags (Mo-Fr) um",
  monday: "Montag",
  tuesday: "Dienstag",
  wednesday: "Mittwoch",
  thursday: "Donnerstag",
  friday: "Freitag",
  saturday: "Samstag",
  sunday: "Sonntag",
  atTime: "um",
  onThe: "Am",
  inThe: "In der",
  ofEvery: "von jeden",
  of: "im",
  first: "Erste",
  second: "Zweite",
  third: "Dritte",
  fourth: "Vierte",
  fifth: "Fünfte",
  last: "Letzte",
  january: "Januar",
  february: "Februar",
  march: "März",
  april: "April",
  may: "Mai",
  june: "Juni",
  july: "Juli",
  august: "August",
  september: "September",
  october: "Oktober",
  november: "November",
  december: "Dezember",
};
