export const en = {
  every: "Every",
  every2: "Every",
  everyMinute: "Every minute",
  hourly: "Hourly",
  daily: "Daily",
  weekly: "Weekly",
  monthly: "Monthly",
  yearly: "Yearly",
  advanced: "Advanced",
  expresion: "Expression",
  seconds: "Second(s)",
  minute: "Minute(s)",
  hour: "Hour(s)",
  days: "Day(s)",
  day: "Day",
  month: "Month",
  week: "Week",
  everyWeekday: "Weekdays (Mon-Fri) at",
  monday: "Monday",
  tuesday: "Tuesday",
  wednesday: "Wednesday",
  thursday: "Thursday",
  friday: "Friday",
  saturday: "Saturday",
  sunday: "Sunday",
  atTime: "at",
  onThe: "On the",
  inThe: "In the",
  ofEvery: "of every",
  of: "of",
  first: "First",
  second: "Second",
  third: "Third",
  fourth: "Fourth",
  fifth: "Fifth",
  last: "Last",
  january: "January",
  february: "February",
  march: "March",
  april: "April",
  may: "May",
  june: "June",
  july: "July",
  august: "August",
  september: "September",
  october: "October",
  november: "November",
  december: "December",
};
